import { Pool, PoolConfig } from 'pg';
import { env } from './env';
import logger from '../utils/logger';

const config: PoolConfig = {
  host: env.dbHost,
  port: env.dbPort,
  user: env.dbUsername,
  password: env.dbPassword,
  database: env.dbDatabase,
  max: env.dbPoolMax,
  idleTimeoutMillis: env.dbPoolIdleTimeout,
  connectionTimeoutMillis: env.dbPoolConnectionTimeout,
};

// If DATABASE_URL is provided, use it instead
if (env.databaseUrl) {
  try {
    const url = new URL(env.databaseUrl);

    config.host = url.hostname;

    // Guard against empty port. `parseInt('')` returns NaN, which the
    // pg driver will silently accept and then fail to connect with.
    config.port = url.port ? parseInt(url.port, 10) : 5432;

    // URL components arrive percent-encoded. Passwords generated by
    // managed providers (Neon, Supabase, etc.) frequently contain
    // characters like $ @ ! # that MUST be decoded before use.
    config.user = url.username ? decodeURIComponent(url.username) : config.user;
    config.password = url.password ? decodeURIComponent(url.password) : config.password;

    config.database = url.pathname.slice(1);

    // ============================================
    // SSL configuration
    // ============================================
    // Neon requires SSL. Their URLs normally include `?sslmode=require`
    // but we also detect the Neon hostname as a fallback so a URL with
    // the query param stripped still works.
    const sslParam = url.searchParams.get('sslmode');
    const isNeon = url.hostname.endsWith('.neon.tech');
    const isLocalhost =
      url.hostname === 'localhost' ||
      url.hostname === '127.0.0.1' ||
      url.hostname === '::1';

    if (sslParam === 'verify-full') {
      config.ssl = { rejectUnauthorized: true };
    } else if (sslParam === 'require' || (isNeon && !isLocalhost)) {
      // Managed providers use self-signed intermediate certs — do not
      // reject unauthorized, or the connection will fail.
      config.ssl = { rejectUnauthorized: false };
    }
  } catch (error) {
    logger.warn(
      '⚠️ Failed to parse DATABASE_URL, using individual config values',
      error instanceof Error ? error.message : error
    );
  }
}

export const pool = new Pool(config);

// Test connection
pool.on('connect', () => {
  logger.info('📦 PostgreSQL connected');
});

pool.on('error', (err) => {
  logger.error('❌ PostgreSQL error:', err);
});

export async function testDatabaseConnection(): Promise<boolean> {
  try {
    const client = await pool.connect();
    const result = await client.query('SELECT NOW() as time');
    client.release();
    logger.info(`✅ Database connected successfully: ${result.rows[0].time}`);
    return true;
  } catch (error) {
    logger.error('❌ Database connection failed:', error);
    return false;
  }
}

export default pool;